# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-17 10:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Army',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('army_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Miniatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miniature_name', models.CharField(max_length=128)),
                ('army', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='army', to='minis.Army')),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='army',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system', to='minis.System'),
        ),
    ]
