# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-17 17:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Army',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(choices=[(1, 'Skin'), (2, 'Weapon_wood'), (3, 'Eyes'), (4, 'Armor'), (5, 'Weapon_steel'), (6, 'Clothes_upper'), (7, 'Clothes_lower'), (8, 'Shoes'), (9, 'Golden_elements'), (10, 'Bone_elements'), (11, 'Base')])),
            ],
        ),
        migrations.CreateModel(
            name='Miniature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('mini_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('army', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minis.Army')),
            ],
        ),
        migrations.CreateModel(
            name='Paint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('miniature', models.ManyToManyField(to='minis.Miniature')),
            ],
        ),
        migrations.CreateModel(
            name='PaintManufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=64)),
                ('paint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minis.Paint')),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='element',
            name='miniature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minis.Miniature'),
        ),
        migrations.AddField(
            model_name='element',
            name='paint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minis.Paint'),
        ),
        migrations.AddField(
            model_name='army',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minis.System'),
        ),
    ]
