# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-17 11:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='PaintManufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=64)),
                ('colors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color', to='minis.Colors')),
            ],
        ),
        migrations.AddField(
            model_name='miniatures',
            name='mini_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='colors',
            name='miniatures',
            field=models.ManyToManyField(related_name='miniatures', to='minis.Miniatures'),
        ),
    ]
