# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-17 17:52
from __future__ import unicode_literals

from django.db import migrations


def add_data(apps, schema_editor):
    System = apps.get_model('minis', 'System')
    Army = apps.get_model('minis', 'Army')

    system = System.objects.create(name='Hordes')
    army = Army.objects.create(name='Trollbloods', system=system)


class Migration(migrations.Migration):

    dependencies = [
        ('minis', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_data),
    ]
