# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-17 13:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minis', '0002_auto_20170117_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementsColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elements', models.IntegerField(choices=[(1, 'Skin'), (2, 'Weapon_wood'), (3, 'Eyes'), (4, 'Armor'), (5, 'Weapon_steel'), (6, 'Clothes_upper'), (7, 'Clothes_lower'), (8, 'Shoes'), (9, 'Golden_elements'), (10, 'Bone_elements'), (11, 'Base')])),
                ('miniatures', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minis', to='minis.Miniatures')),
                ('paints', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_elements', to='minis.Colors')),
            ],
        ),
    ]
