# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-18 08:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minis', '0003_auto_20170118_0856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paintmanufacturer',
            name='paint',
        ),
        migrations.AddField(
            model_name='paint',
            name='manufacturer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='minis.PaintManufacturer'),
            preserve_default=False,
        ),
    ]
